name: Build YantoNet Printer APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Versi diperbarui

    - name: Set up JDK 17
      uses: actions/setup-java@v4 # Versi diperbarui
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3 # Versi diperbarui
      with:
        arguments: :app:assembleDebug

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4 # Versi diperbarui (INI YANG PALING PENTING)
      with:
        name: yantonet-printer-app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
